# Generated by Django 3.0.7 on 2020-06-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200617_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='headline',
            new_name='title',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
        migrations.AddField(
            model_name='starquestion',
            name='star',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StarAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
