# Generated by Django 3.0.7 on 2020-06-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200621_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
    ]
