# Generated by Django 3.0.7 on 2020-06-22 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_question_favorite_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='starquestion',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='favorite_of',
            field=models.ManyToManyField(related_name='favorite_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StarAnswer',
        ),
        migrations.DeleteModel(
            name='StarQuestion',
        ),
    ]
