# Generated by Django 3.0.7 on 2020-09-20 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200622_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='favorite_of',
            field=models.ManyToManyField(blank=True, related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
